name: SignMaker
version: ${build.version}
author: Schmoller

main: au.com.addstar.signmaker.SignMakerPlugin

commands:
  signmaker:
    usage: /<command> <font> <justification> <material> <text>

permissions:
  signmaker.write:
    default: op
    children:
      signmaker.undo: true

  signmaker.undo:
    default: op
    
  signmaker.create:
    default: op
    children:
      signmaker.undo: true

  signmaker.set.text:
    default: op
  signmaker.set.font:
    default: op
  signmaker.set.justification:
    default: op
  signmaker.set.material:
    default: op
  signmaker.redraw:
    default: op
  signmaker.remove:
    default: op