name: SignMaker
version: ${build.version}
author: Schmoller

main: au.com.addstar.signmaker.SignMakerPlugin

commands:
  signmaker:
    usage: /<command> <font> <justification> <material> <text>

permissions:
  signmaker.write:
    default: op
    children:
      signmaker.undo: true

  signmaker.undo:
    default: op
