name: SuperSigns
version: ${plugin.version}
author: Schmoller
api-version: ${spigot.api.version}
main: au.com.addstar.signmaker.SignMakerPlugin

commands:
  signmaker:
    aliases: [supersigns,ssigns]

permissions:
  signmaker.*:
    default: op
    children:
      signmaker.write: true
      signmaker.undo: true
      signmaker.create: true
      signmaker.remove: true
      signmaker.set.text: true
      signmaker.set.font: true
      signmaker.set.justification: true
      signmaker.set.material: true
      signmaker.redraw: true
      signmaker.transition: true
      signmaker.play: true
      
  signmaker.write:
    default: op
    children:
      signmaker.undo: true

  signmaker.undo:
    default: op
    
  signmaker.create:
    default: op
    children:
      signmaker.undo: true
  signmaker.remove:
    default: op

  signmaker.set.text:
    default: op
  signmaker.set.font:
    default: op
  signmaker.set.justification:
    default: op
  signmaker.set.material:
    default: op
  signmaker.redraw:
    default: op
  
  signmaker.transition:
    default: op
  
  signmaker.list.fonts:
    default: op
  signmaker.play:
    default: op